test: rerun pipeline

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -17,9 +17,11 @@ jobs:
       uses: docker/setup-buildx-action@v3
     
     - name: Read Version File
+      id: read-version
       run: |
         VERSION=$(cat version.txt)
         echo "Version from file: $VERSION"
+        echo "VERSION=$VERSION" >> $GITHUB_ENV
 
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
@@ -28,19 +30,19 @@ jobs:
         password: ${{ secrets.DOCKER_PASSWORD }}
     
     - name: Output version
-      run: echo "New version is ${{ VERSION }}"
+      run: echo "New version is ${{ env.VERSION }}"
 
     - name: Build Docker image
       id: build-docker
       run: |
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/web-grader:${{ VERSION }} .
+        docker build -t ${{ secrets.DOCKER_USERNAME }}/web-grader:${{ env.VERSION }} .
       continue-on-error: true
 
     - name: Push Docker image
       id: push-docker
       run: |
-        docker push ${{ secrets.DOCKER_USERNAME }}/web-grader:${{ VERSION }}
-        docker tag ${{ secrets.DOCKER_USERNAME }}/web-grader:${{ VERSION }} ${{ secrets.DOCKER_USERNAME }}/web-grader:latest
+        docker push ${{ secrets.DOCKER_USERNAME }}/web-grader:${{ env.VERSION }}
+        docker tag ${{ secrets.DOCKER_USERNAME }}/web-grader:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/web-grader:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/web-grader:latest
       continue-on-error: true
 
@@ -49,12 +51,12 @@ jobs:
       run: |
         echo "Push failed, deleting tag..."
         git fetch --tags
-        git tag -d ${{ VERSION }} || echo "Tag not found locally, skipping deletion..."
-        git push --delete origin ${{ VERSION }} || echo "Tag not found on remote, skipping deletion..."
+        git tag -d ${{ env.VERSION }} || echo "Tag not found locally, skipping deletion..."
+        git push --delete origin ${{ env.VERSION }} || echo "Tag not found on remote, skipping deletion..."
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
-    - name: remove file version
+    - name: Remove version file
       run: |
         rm version.txt
         git config user.name "github-actions[bot]"
@@ -62,5 +64,3 @@ jobs:
         git add .
         git commit -m "Remove version.txt"
         git push
-
-
